server:
  port: 8080

spring:
  application:
    name: Hello-World
  profiles:
    active: local

  datasource:
    url: jdbc:h2:mem:testdb
    username: sa
    password: sa
    driverClassName: org.h2.Driver

  h2:
    console.enabled: true

mybatis-plus:
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl